# this file is autogenerated by .github/workflows/update.yml
{
  url = "https://github.com/AtaraxiaSjel/nix-index-database/releases/download/2026-03-08-042613/index-";
  hashes = {
    x86_64-linux = "sha256-5yGmlx4nVD7pBXCzGVBXv1wkNeJ3x0MQ5GTBXFl4Q7k=";
    aarch64-linux = "sha256-qDOFObhAhbNmHY6f3obO/reimaz/vNKidjwjZ9GnG8I=";
    x86_64-darwin = "sha256-iNsGtXTMFS3zRWUOHnx2clPtmIzz94zumdvM6bUNfes=";
    aarch64-darwin = "sha256-GkEh09WkmeyMwyN6gKOc8pvmAT1Gc6BeJTHTS2ilsxY=";
    x86_64-linux-small = "sha256-5SFwQDYqmL4P4py+Upb+wRZyZpSN+azWcFAlKqJzGOA=";
    aarch64-linux-small = "sha256-IuKNElPGdCKqiqSzy6DNEIqBe+DkLmNWMYq4Nxhjjyw=";
    x86_64-darwin-small = "sha256-gk0Zyvv2yjKed14CkiRWoLvxI4iw4He293w5H/Qmq9c=";
    aarch64-darwin-small = "sha256-DwcqTCcaT9qPIp3AfbwxNWuZK0dxIuEYvYvF0atNO+A=";
  };
}
