# this file is autogenerated by .github/workflows/update.yml
{
  url = "https://github.com/AtaraxiaSjel/nix-index-database/releases/download/2025-12-21-035217/index-";
  hashes = {
    x86_64-linux = "sha256-nlkhwGCpeCYNSLprperPhIceisRXdWANBH///UxAFvw=";
    aarch64-linux = "sha256-GUoMcU5abkGQkEEXAFAY2kEkjVYUnkD6xXs8nsrpQus=";
    x86_64-darwin = "sha256-JobYH506fn/viJ7S5rYUxtyonOZxh0I838f+fwUCGbc=";
    aarch64-darwin = "sha256-lmk0TXx/U2O1rJwbdpWHVkqd0eYzVmFQ1UbkC6bZXYs=";
    x86_64-linux-small = "sha256-cSkbCOrjvnrxWipmSn0Epk8+twTV+njIZKvwj/n7imc=";
    aarch64-linux-small = "sha256-wxirzEpTQoxIqmSg7sd7eNFle/UEA+Wr6ndhe5qACTE=";
    x86_64-darwin-small = "sha256-AbuOoLDiZ3cbXxM+v0HbKa2gs75T9AvYk9MCAIQkmn8=";
    aarch64-darwin-small = "sha256-pp7Bo1r5wt+9GGt6OriDsi9YBkMyuLmcNDRICiCo3hc=";
  };
}
