# this file is autogenerated by .github/workflows/update.yml
{
  url = "https://github.com/AtaraxiaSjel/nix-index-database/releases/download/2026-05-17-060330/index-";
  hashes = {
    x86_64-linux = "sha256-qauGYsSmS7YG9aKUQa5CsYqF+UvZG3GdmnrYpG4gbTU=";
    aarch64-linux = "sha256-gJXl6RomfR+yS5BNHGdTTXkWbt04iyfCvvQft5bLdSY=";
    x86_64-darwin = "sha256-UasOqANfLbQgR5Jx8YfPTWQV3yTbxChCF7hefNnIeN8=";
    aarch64-darwin = "sha256-dfZDTIHNdEx+jly8ArCTA8jCgmTpcADjlh2KSH5d+Ic=";
    x86_64-linux-small = "sha256-G9GJ9doyuBeXD8zxYK3axP/S4Knwr4JIxM+f7HfEZF0=";
    aarch64-linux-small = "sha256-ItbXRU37SdRf75+T6jBCCXCQTHNeWtmU3gylCpeI6BA=";
    x86_64-darwin-small = "sha256-ppV6P/XCV97axagRMCrHlayOS3T69QOeL9Gp+vbIYWw=";
    aarch64-darwin-small = "sha256-kqv8+3OLEu8b0bsRtMyEAK6JapSnlkBtrotv6CZGou8=";
  };
}
